/* eslint-disable no-console */
// Load .env.local first (what the Next.js app uses), then fall back to .env.
// `dotenv/config` alone only loads .env, which means running this script
// outside Next would target a different DB than the running app.
import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
loadEnv({ path: ".env" });

import mongoose from "mongoose";
import { connectDB } from "../lib/db/mongoose";
import { User } from "../lib/models/user";
import { Project } from "../lib/models/project";
import { Task } from "../lib/models/task";
import { Comment } from "../lib/models/comment";
import { Activity } from "../lib/models/activity";
import { Notification } from "../lib/models/notification";
import bcrypt from "bcryptjs";

const DEMO_USERS = [
  { name: "Ada Lovelace", email: "admin@demo.com", role: "admin" as const, password: "admin123" },
  { name: "Grace Hopper", email: "manager@demo.com", role: "manager" as const, password: "manager123" },
  { name: "Alan Turing", email: "member@demo.com", role: "member" as const, password: "member123" },
];

const PROJECT_BODY = {
  name: "Q1 Product Launch",
  description: "Plan, build, and ship our v1 platform launch by end of Q1.",
  status: "active" as const,
  deadline: new Date(Date.now() + 1000 * 60 * 60 * 24 * 45), // 45 days
};

const TASKS = [
  { title: "Design landing page", priority: "high" as const, status: "in_progress" as const, daysFromNow: 5, assignee: 0 },
  { title: "Set up CI/CD pipeline", priority: "high" as const, status: "todo" as const, daysFromNow: 7, assignee: 0 },
  { title: "Write onboarding docs", priority: "medium" as const, status: "todo" as const, daysFromNow: 14, assignee: 2 },
  { title: "Set up analytics dashboard", priority: "medium" as const, status: "todo" as const, daysFromNow: 21, assignee: 1 },
  { title: "Run launch-day smoke tests", priority: "high" as const, status: "todo" as const, daysFromNow: 40, assignee: 1 },
  { title: "Define pricing page copy", priority: "low" as const, status: "completed" as const, daysFromNow: -3, assignee: 1 },
  { title: "API: project endpoints", priority: "high" as const, status: "in_progress" as const, daysFromNow: 10, assignee: 0 },
  { title: "Auth: password reset flow", priority: "medium" as const, status: "todo" as const, daysFromNow: 18, assignee: 2 },
  { title: "Wire up notifications", priority: "medium" as const, status: "todo" as const, daysFromNow: 25, assignee: 0 },
  { title: "Polish empty states", priority: "low" as const, status: "todo" as const, daysFromNow: 30, assignee: 2 },
  { title: "Write launch blog post", priority: "medium" as const, status: "todo" as const, daysFromNow: 35, assignee: 1 },
  { title: "Coordinate press outreach", priority: "low" as const, status: "completed" as const, daysFromNow: -1, assignee: 1 },
];

async function main() {
  await connectDB();
  console.log("✓ connected");

  console.log("• wiping collections");
  await Promise.all([User.deleteMany({}), Project.deleteMany({}), Task.deleteMany({}), Comment.deleteMany({}), Activity.deleteMany({}), Notification.deleteMany({})]);

  console.log("• creating users");
  const users: Array<{ _id: mongoose.Types.ObjectId; name: string; email: string; role: string }> = [];
  for (const u of DEMO_USERS) {
    const passwordHash = await bcrypt.hash(u.password, 10);
    const created = await User.create({ name: u.name, email: u.email, role: u.role, passwordHash });
    users.push({ _id: created._id as mongoose.Types.ObjectId, name: created.name, email: created.email, role: created.role });
  }
  const [admin, manager, member] = users;
  if (!admin || !manager || !member) throw new Error("seed: user creation failed");

  console.log("• creating project");
  const project = await Project.create({
    ...PROJECT_BODY,
    ownerId: admin._id,
    memberIds: [admin._id, manager._id, member._id],
  });

  console.log("• creating tasks");
  const createdTasks: Array<{ _id: mongoose.Types.ObjectId; title: string }> = [];
  for (const t of TASKS) {
    const assignee = users[t.assignee] ?? admin;
    const task = await Task.create({
      title: t.title,
      description: `Task: ${t.title}. Generated by seed script.`,
      projectId: project._id,
      assigneeId: assignee._id,
      createdBy: admin._id,
      priority: t.priority,
      status: t.status,
      dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * t.daysFromNow),
    });
    createdTasks.push({ _id: task._id as mongoose.Types.ObjectId, title: task.title });
  }

  console.log("• creating comments");
  const landingTask = createdTasks[0];
  const apiTask = createdTasks[6];
  if (landingTask && apiTask) {
    await Comment.create({ taskId: landingTask._id, authorId: manager._id, body: "Hero copy should emphasize the team workflow story." });
    await Comment.create({ taskId: landingTask._id, authorId: member._id, body: "Pushed a first draft of the section above the fold." });
    await Comment.create({ taskId: apiTask._id, authorId: admin._id, body: "We need to lock the contract before the front-end can wire it up." });
  }

  console.log("• logging activity");
  await Activity.create({ projectId: project._id, actorId: admin._id, type: "project_created", message: `${admin.name} created project "${project.name}"` });
  for (const t of createdTasks.slice(0, 3)) {
    await Activity.create({ projectId: project._id, taskId: t._id, actorId: admin._id, type: "task_created", message: `${admin.name} created task "${t.title}"` });
  }

  console.log("\n✓ seed complete\n");
  console.log("Demo accounts:");
  for (const u of DEMO_USERS) console.log(`  ${u.role.padEnd(8)} ${u.email}  /  ${u.password}`);
  console.log("");

  await mongoose.disconnect();
  process.exit(0);
}

main().catch((err) => {
  console.error("✗ seed failed:", err);
  process.exit(1);
});
